### ISSUE TITLE
其他目录下执行报错

### ISSUE THREAD

**Issue by Gee233** [BarryYan/daily-warm#4]
超赞！所以我为它写了个自启动脚本，但是在其他目录运行会出现如下错误：

    # /usr/local/src/daily-warm-1.0.0/dwm.out
    2019/12/24 09:45:36 Load .env file error: open .env: no such file or directory

**Comment by ISeekTruth** [comment]
你需要在 dwm.out 文件同级目录下有一个 .env 配置文件
